version: '3.8'
services:
  mongo:
    image: mongo:6
    container_name: taskmaster-mongo
    restart: always
    ports:
      - "27017:27017"
    volumes:
      - mongo-data:/data/db
  backend:
    build: ./server
    container_name: taskmaster-backend
    restart: always
    ports:
      - "5000:5000"
    environment:
      - MONGO_URI=mongodb+srv://dtharanga023_db_user:2fcV3CrAa3qvpZac@cluster0.xfcmp4d.mongodb.net/taskmaster?retryWrites=true&w=majority&appName=Cluster0
      - JWT_SECRET=3f8b2c1e-9a4d-4e2b-8c7a-2d1f6e5b7c8d
    depends_on:
      - mongo
  frontend:
    build: ./client
    container_name: taskmaster-frontend
    restart: always
    ports:
      - "3000:3000"
    environment:
      - REACT_APP_API_URL=http://localhost:5000
    depends_on:
      - backend
volumes:
  mongo-data:
